### ISSUE TITLE
[ BUG ] Uber APIHarness failing for RTR ListFiles*

### ISSUE THREAD

**Issue by hiddenillusion** [CrowdStrike/falconpy#750] opened 2022-08-16 20:21 UTC
**Describe the bug**
The Uber class does not work as expected when attempting to use RTR's ListFiles/ListFilesV2

**To Reproduce**

Both Service class examples work as expected:
```
from falconpy import RealTimeResponse
falcon = RealTimeResponse(client_id=client_id, client_secret=client_secret)
resp = falcon.list_files(session_id=session_id)

...

from falconpy import RealTimeResponse
falcon = RealTimeResponse(client_id=client_id, client_secret=client_secret)
resp = falcon.RTR_ListFilesV2(session_id=session_id) 
```

However, attempting to use the Uber class as documented raises error code 400 `No Session ID provided` :

```
from falconpy import APIHarness
falcon = APIHarness(client_id=client_id, client_secret=client_secret)
resp = falcon.command("RTR_ListFilesV2", session_id=session_id)
```

Debugging [`command()`](https://github.com/CrowdStrike/falconpy/blob/c5c14029a9c03ded18983c7dcba302c6d1ac7836/src/falconpy/api_complete.py#L277), I see that `session_id` is picked up as a kwarg:
```
kwargs: {'session_id': '<SESSION_ID>', 'action': 'RTR_ListFilesV2'}
``` 

and tracing the flow in [`perform_request()`](https://github.com/CrowdStrike/falconpy/blob/c5c14029a9c03ded18983c7dcba302c6d1ac7836/src/falconpy/_util.py#L256) I see it gets populated into `params`:
```
kwargs: {'method': 'GET', 'body': {}, 'data': {}, 'params': {'session_id': '<SESSION_ID>}, 'files': [], 'verify': True, 'proxy': None, 'timeout': None, 'user_agent': None, 'expand_result': False}

```

**Expected behavior**
The `session_id` argument is properly identified.

**Environment (please complete the following information):**
 - Python: 3.9
 - FalconPy: 1.1.6

**Additional context**

**Comment by jshcodes** [comment] 2022-08-19 23:38
Hi @hiddenillusion -

We are able to recreate this issue and are investigating the underlying root cause.

Thank you for providing this detail and reporting this!

**Comment by jshcodes** [comment] 2022-08-20 00:16
Found it.  These operations prefer a NoneType instead of an empty dictionary for the body payload. Adding these two operation IDs to our "Prefer_NoneType" list appears to resolve the issue.  This fix will be included in our next release.

Thank you again for identifying this! 😄

**Closed** 2022-08-30 20:18 UTC
Labels: bug :bug:, RTR, uber
